config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :admin_users
    resources :athletes
    resources :featured_photos
    resources :news_articles
    resources :sports, only: [:index, :show]
    resources :testimonials

    root to: "admin_users#index"
  end

  devise_for :admin_users

  root to: 'pages#index'

  resources :news_articles
  resources :featured_photos
  resources :athletes

  get '/womens-basketball', to: 'sports#womens_basketball'
  get '/mens-basketball', to: 'sports#mens_basketball'
  get '/football', to: 'sports#football'

  get '/womens-basketball/featured', to: 'sports#womens_basketball_featured'
  get '/mens-basketball/featured', to: 'sports#mens_basketball_featured'
  get '/football/featured', to: 'sports#football_featured'

  get 'womens-basketball/wnba', to: 'sports#womens_basketball_wnba'
  get 'womens-basketball/overseas', to: 'sports#womens_basketball_overseas'

  get 'football/nfl', to: 'sports#football_nfl'
  get 'football/free-agent', to: 'sports#football_free_agent'

  get '/womens-basketball/about', to: 'pages/womens_basketball#about'
  get '/womens-basketball/team', to: 'pages/womens_basketball#team'
  get '/womens-basketball/testimonials', to: 'pages/womens_basketball#testimonials'

  get '/womens-basketball/professional-management', to: 'pages/womens_basketball#professional_management'
  get '/womens-basketball/career', to: 'pages/womens_basketball#career_development'
  get '/womens-basketball/personal-management', to: 'pages/womens_basketball#personal_management'
  get '/womens-basketball/marketing', to: 'pages/womens_basketball#marketing'

  get '/womens-basketball/contact', to: 'pages/womens_basketball#contact'

  get '/mens-basketball/about', to: 'pages/mens_basketball#about'
  get '/mens-basketball/team', to: 'pages/mens_basketball#team'
  get '/mens-basketball/testimonials', to: 'pages/mens_basketball#testimonials'

  get '/mens-basketball/draft', to: 'pages/mens_basketball#draft_preparation'
  get '/mens-basketball/training', to: 'pages/mens_basketball#training'
  get '/mens-basketball/marketing', to: 'pages/mens_basketball#marketing'
  get '/mens-basketball/career', to: 'pages/mens_basketball#career_development'

  get '/mens-basketball/contact', to: 'pages/mens_basketball#contact'

  get '/football/about', to: 'pages/football#about'
  get '/football/team', to: 'pages/football#team'
  get '/football/testimonials', to: 'pages/football#testimonials'

  get '/football/professional-management', to: 'pages/football#professional_management'
  get '/football/marketing', to: 'pages/football#marketing'
  get '/football/career', to: 'pages/football#career_development'
  get '/football/wealth-management', to: 'pages/football#wealth_management'

  get '/football/contact', to: 'pages/football#contact'

  
  get 'boris', to: 'pages/womens_basketball#boris'
  get 'carolina', to: 'pages/womens_basketball#carolina'
  get 'ticha', to: 'pages/womens_basketball#ticha'
  get 'sammy', to: 'pages/womens_basketball#sammy'
  get 'jonathan', to: 'pages/womens_basketball#jonathan'

  get 'boris-mens', to: 'pages/mens_basketball#boris', as: 'boris_mens'
  get 'michael', to: 'pages/mens_basketball#michael', as: 'michael'
  get 'sammy-mens', to: 'pages/mens_basketball#sammy', as: 'sammy_mens'
  get 'jonathan-mens', to: 'pages/mens_basketball#jonathan', as: 'jonathan_mens'

  get 'boris-football', to: 'pages/football#boris', as: 'boris_football'
  get 'chad', to: 'pages/football#chad'

end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :athletes, dependent: :destroy
  has_many :featured_photos, dependent: :destroy
  has_many :news_articles, dependent: :destroy

  def womens_basketball?
    return true if self.type_id == 0
  end

  def mens_basketball?
    return true if self.type_id == 1
  end

  def football?
    return true if self.type_id == 2
  end
end

app/controllers/admin/sports_controller.rb
module Admin
  class SportsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Sport.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Sport.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  has_scope :available, type: :boolean
  has_scope :unavailable, type: :boolean
  has_scope :position
  has_scope :wnba_status

  def womens_basketball_featured
    @sport = Sport.find_by_type_id(0)
    @news_articles = apply_scopes(NewsArticle).where(sport_id: 3)
  end

  def mens_basketball_featured
    @sport = Sport.find_by_type_id(1)
    @news_articles = apply_scopes(NewsArticle).where(sport_id: 4)
  end

  def football_featured
    @sport = Sport.find_by_type_id(2)
    @news_articles = apply_scopes(NewsArticle).where(sport_id: 2)
  end
  
  def womens_basketball_wnba
    @sport = Sport.find_by_type_id(0)
    @athletes = apply_scopes(Athlete).where(sport_id: 3).where(wnba_status: 'WNBA')
    @guards = @athletes.where(position: 'Guard').to_a
    @guards.sort! {|a,b| a.last_name.downcase <=> b.last_name.downcase }
    @forwards = @athletes.where(position: 'Forward').to_a
    @forwards.sort! {|a,b| a.last_name.downcase <=> b.last_name.downcase }
    @centers = @athletes.where(position: 'Center').to_a
    @centers.sort! {|a,b| a.last_name.downcase <=> b.last_name.downcase }
  end

  def womens_basketball_overseas
    @sport = Sport.find_by_type_id(0)
    @athletes = apply_scopes(Athlete).where(sport_id: 3).where(wnba_status: 'Professional Overseas')
    @guards = @athletes.where(position: 'Guard').to_a
    @guards.sort! {|a,b| a.last_name.downcase <=> b.last_name.downcase }
    @forwards = @athletes.where(position: 'Forward').to_a
    @forwards.sort! {|a,b| a.last_name.downcase <=> b.last_name.downcase }
    @centers = @athletes.where(position: 'Center').to_a
    @centers.sort! {|a,b| a.last_name.downcase <=> b.last_name.downcase }
  end
  
  def mens_basketball
    @sport = Sport.find_by_type_id(1)
    @athletes = apply_scopes(Athlete).where(sport_id: 4)
  end

  def football_nfl
    @sport = Sport.find_by_type_id(2)
    @athletes = apply_scopes(Athlete).where(sport_id: 2).where(nfl_status: 'NFL')
  end

  def football_free_agent
    @sport = Sport.find_by_type_id(2)
    @athletes = apply_scopes(Athlete).where(sport_id: 2).where(nfl_status: 'Free Agent')
  end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_athlete.html.erb
<div class="grid-item" onclick="">
  <%= image_tag athlete.photo.url, alt: 'Tavon Wilson', class: 'grid-item-image' %>
  <div class="grid-item-view">
    <h2 class="grid-item-view-title">
      <%= "#{athlete.first_name} #{athlete.last_name}" %>
    </h2>
    <ul class="grid-item-view-list">
      <li>
        <span>Position:</span>
        <span><%= athlete.position %></span>
      </li>
      <% unless athlete.american_team_name.empty? %>
        <li>
          <span>Team:</span>
          <span><%= link_to athlete.american_team_name, athlete.american_team_url, class: 'red' %></span>
        </li>
      <% end %>
      <li>
        <span>Born:</span>
        <span><%= athlete.birthdate.strftime("%m/%d/%Y") if athlete.birthdate %></span>
      </li>
      <li>
        <span>Height:</span>
        <span><%= athlete.height %></span>
      </li>
      <li>
        <span>Weight:</span>
        <span><%= athlete.weight %></span>
      </li>
      <li>
        <span><%= link_to 'Website', athlete.website_url, class: 'red' %></span>
      </li>
      <li>
        <span>College:</span>
        <span><%= athlete.college %></span>
      </li>
      <% if @sport.id == 4 %>
      <li>
        <div class="flag-container">
          <%= image_tag flag_url(athlete), class: 'flag-icon', alt: 'US' %>
        </div>
      </li>
      <% end %>
      <li>
        <% if @sport.id == 4 %>
          <a href="<%= athlete_path(athlete.id) %>" class="grid-item-view-button">FULL BIOGRAPHY</a>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/sports/_woman_athlete.html.erb
<div class="athlete-list-item">
  <div class="flag-container">
    <%= image_tag flag_url(woman_athlete), class: 'flag-icon', alt: 'US' %>
  </div>
  <h3 class="athlete-list-name">
    <a href="<%= athlete_path(woman_athlete.id) %>">
      <%= "#{woman_athlete.first_name} #{woman_athlete.last_name}" %>
    </a>
  </h3>
  
</div>

app/views/sports/_womens_basketball.html.erb
  <div class="column">
    <h2 class="column-header">Guards</h2>
    <%= render partial: 'woman_athlete', collection: @guards %>
  </div>

  <div class="column">
    <h2 class="column-header">Forwards</h2>
    <%= render partial: 'woman_athlete', collection: @forwards %>
  </div>

  <div class="column">
    <h2 class="column-header">Centers</h2>
    <%= render partial: 'woman_athlete', collection: @centers %>
  </div>

app/views/sports/football.html.erb
<main class="grid">
  <% 9.times do |_| %>
    <%= render partial: 'athlete', collection: @athletes %>
  <% end %>
</main>

app/views/sports/football_featured.html.erb
<main class="sports">
  <section id="featured">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/football/photo1.jpg" class="featured-img" />
        </div>

        <div class="item">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/football/photo2.jpg" class="featured-img" />
        </div>

        <div class="item active">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/football/photo3.jpg" class="featured-img" />
        </div>

        <div class="item">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/football/photo4.jpg" class="featured-img" />
        </div>

        <div class="item">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/football/photo5.jpg" class="featured-img" />
        </div>
      </div>
    </div>
  </section>

  <section class="news-section">
    <h2>Football News</h2>

    <% @news_articles.each do | article | %>
      <a href="<%= article.url %>">
        <h3 class="red"><%= article.headline %></h3>
        <h4><%= article.date_posted %></h4>
      </a>
    <% end %>
  </section>
</main>

app/views/sports/football_free_agent.html.erb
<main class="sports grid">

  <%= render partial: 'athlete', collection: @athletes %>

</main>

app/views/sports/football_nfl.html.erb
<main class="sports grid">
  <%= render partial: 'athlete', collection: @athletes %>
</main>

app/views/sports/mens_basketball.html.erb
<main class="sports grid">

  <header class="filter-header">
    <ul class="left-filter">
      <li><%= link_to 'Centers', mens_basketball_path(position: 'Center'), class: "filter-link" %></li>
      <li><%= link_to 'Forwards', mens_basketball_path(position: 'Forward'), class: "filter-link" %></li>
      <li><%= link_to 'Guards', mens_basketball_path(position: 'Guard'), class: "filter-link" %></li>
    </ul>
  </header>
  
  <%= render partial: 'athlete', collection: @athletes %>

</main>

app/views/sports/mens_basketball_featured.html.erb
<main class="sports">
  <section id="featured">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/mens_basketball/photo1.jpg" class="featured-img" />
        </div>

        <div class="item">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/mens_basketball/photo2.jpg" class="featured-img" />
        </div>

        <div class="item active">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/mens_basketball/photo3.jpg" class="featured-img" />
        </div>

        <div class="item active">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/mens_basketball/photo4.jpg" class="featured-img" />
        </div>
      </div>
    </div>
  </section>

  <section class="news-section">
    <h2>Mens Basketball News</h2>

    <% @news_articles.each do | article | %>
      <a href="<%= article.url %>">
        <h3 class="red"><%= article.headline %></h3>
        <h4><%= article.date_posted %></h4>
      </a>
    <% end %>
  </section>
</main>

app/views/sports/womens_basketball.html.erb
<main class="grid">
  <header class="filter-header">
    <ul class="left-filter">
      <li><%= link_to 'WNBA', womens_basketball_path(wnba_status: 'WNBA'), class: "filter-link" %></li>
      <li><%= link_to 'Professional Overseas', womens_basketball_path(wnba_status: 'Professional Overseas'), class: "filter-link" %></li>
    </ul>

    <ul class="right-filter">
      <li><%= link_to 'All', womens_basketball_path, class: "filter-link" %></li>
      <li><%= link_to 'Available', womens_basketball_path(available: true), class: "filter-link" %></li>
      <li><%= link_to 'Unavailable', womens_basketball_path(available: false), class: "filter-link" %></li>
    </ul>
  </header>

  <div class="column">
    <h2 class="column-header">Guards</h2>
    <% 9.times do |_| %>
      <%= render partial: 'woman_athlete', collection: @athletes.where(position: "Guard") %>
    <% end %>
  </div>

  <div class="column">
    <h2 class="column-header">Forwards</h2>
    <% 9.times do |_| %>
      <%= render partial: 'woman_athlete', collection: @athletes.where(position: "Forward") %>
    <% end %>
  </div>

  <div class="column">
    <h2 class="column-header">Centers</h2>
    <% 9.times do |_| %>
      <%= render partial: 'woman_athlete', collection: @athletes.where(position: "Center") %>
    <% end %>
  </div>
</main>

app/views/sports/womens_basketball_featured.html.erb
<main>
  <section id="featured">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/womens_basketball/photo1.jpg" class="featured-img" />
        </div>

        <div class="item">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/womens_basketball/photo2.jpg" class="featured-img" />
        </div>

        <div class="item active">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/womens_basketball/photo3.jpg" class="featured-img" />
        </div>

        <div class="item active">
          <img src="https://s3.amazonaws.com/sig-sports/images/featured/womens_basketball/photo4.jpg" class="featured-img" />
        </div>
      </div>
    </div>
  </section>

  <section class="news-section">
    <h2>Womens Basketball News</h2>

    <% @news_articles.each do | article | %>
      <a href="<%= article.url %>">
        <h3 class="red"><%= article.headline %></h3>
        <h4><%= article.date_posted %></h4>
      </a>
    <% end %>
  </section>
</main>

app/views/sports/womens_basketball_overseas.html.erb
<main class="sports grid">
  <header class="filter-header">
    <ul class="right-filter">
      <li><%= link_to 'Available', womens_basketball_overseas_path(available: true), class: "filter-link" %></li>
      <li><%= link_to 'Unavailable', womens_basketball_overseas_path(unavailable: true), class: "filter-link" %></li>
    </ul>
  </header>

  <h1>CURRENT OVERSEAS CLIENTS</h1>

  <%= render partial: 'womens_basketball' %>
  
</main>
<footer class="sports slogan-footer">
  <h3 id="slogan">Taking you to the next level...</h3>  
</footer>

app/views/sports/womens_basketball_wnba.html.erb
<main class="sports grid">
  <header class="filter-header">
    <ul class="right-filter">
      <li><%= link_to 'Available', womens_basketball_wnba_path(available: true), class: "filter-link" %></li>
      <li><%= link_to 'Unavailable', womens_basketball_wnba_path(unavailable: true), class: "filter-link" %></li>
    </ul>
  </header>

  <h1>CURRENT WNBA CLIENTS</h1>

  <%= render partial: 'womens_basketball' %>
</main>
<footer class="sports slogan-footer">
  <h3 id="slogan">Taking you to the next level...</h3>  
</footer>