config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :admin_users
    resources :athletes
    resources :featured_photos
    resources :news_articles
    resources :sports, only: [:index, :show]
    resources :testimonials

    root to: "admin_users#index"
  end

  devise_for :admin_users

  root to: 'pages#index'

  resources :news_articles
  resources :featured_photos
  resources :athletes

  get '/womens-basketball', to: 'sports#womens_basketball'
  get '/mens-basketball', to: 'sports#mens_basketball'
  get '/football', to: 'sports#football'

  get '/womens-basketball/featured', to: 'sports#womens_basketball_featured'
  get '/mens-basketball/featured', to: 'sports#mens_basketball_featured'
  get '/football/featured', to: 'sports#football_featured'

  get 'womens-basketball/wnba', to: 'sports#womens_basketball_wnba'
  get 'womens-basketball/overseas', to: 'sports#womens_basketball_overseas'

  get 'football/nfl', to: 'sports#football_nfl'
  get 'football/free-agent', to: 'sports#football_free_agent'

  get '/womens-basketball/about', to: 'pages/womens_basketball#about'
  get '/womens-basketball/team', to: 'pages/womens_basketball#team'
  get '/womens-basketball/testimonials', to: 'pages/womens_basketball#testimonials'

  get '/womens-basketball/professional-management', to: 'pages/womens_basketball#professional_management'
  get '/womens-basketball/career', to: 'pages/womens_basketball#career_development'
  get '/womens-basketball/personal-management', to: 'pages/womens_basketball#personal_management'
  get '/womens-basketball/marketing', to: 'pages/womens_basketball#marketing'

  get '/womens-basketball/contact', to: 'pages/womens_basketball#contact'

  get '/mens-basketball/about', to: 'pages/mens_basketball#about'
  get '/mens-basketball/team', to: 'pages/mens_basketball#team'
  get '/mens-basketball/testimonials', to: 'pages/mens_basketball#testimonials'

  get '/mens-basketball/draft', to: 'pages/mens_basketball#draft_preparation'
  get '/mens-basketball/training', to: 'pages/mens_basketball#training'
  get '/mens-basketball/marketing', to: 'pages/mens_basketball#marketing'
  get '/mens-basketball/career', to: 'pages/mens_basketball#career_development'

  get '/mens-basketball/contact', to: 'pages/mens_basketball#contact'

  get '/football/about', to: 'pages/football#about'
  get '/football/team', to: 'pages/football#team'
  get '/football/testimonials', to: 'pages/football#testimonials'

  get '/football/professional-management', to: 'pages/football#professional_management'
  get '/football/marketing', to: 'pages/football#marketing'
  get '/football/career', to: 'pages/football#career_development'
  get '/football/wealth-management', to: 'pages/football#wealth_management'

  get '/football/contact', to: 'pages/football#contact'

  
  get 'boris', to: 'pages/womens_basketball#boris'
  get 'carolina', to: 'pages/womens_basketball#carolina'
  get 'ticha', to: 'pages/womens_basketball#ticha'
  get 'sammy', to: 'pages/womens_basketball#sammy'
  get 'jonathan', to: 'pages/womens_basketball#jonathan'

  get 'boris-mens', to: 'pages/mens_basketball#boris', as: 'boris_mens'
  get 'michael', to: 'pages/mens_basketball#michael', as: 'michael'
  get 'sammy-mens', to: 'pages/mens_basketball#sammy', as: 'sammy_mens'
  get 'jonathan-mens', to: 'pages/mens_basketball#jonathan', as: 'jonathan_mens'

  get 'boris-football', to: 'pages/football#boris', as: 'boris_football'
  get 'chad', to: 'pages/football#chad'

end

app/views/shared/_sidebar.html.erb
<div id="responsive-burger"><a href="#">&equiv;</a></div>

<% unless @sport.blank? %>
  <div id="sidebar">
    <header>
      <h1>
        <a href="<%= root_path %>">
          <%= image_tag 'logo.png', alt: 'SIG Sports' %>
        </a>
      </h1>
    </header>

    <% if @sport.womens_basketball? %>
      <%= render 'shared/sidebar_womens_basketball' %>
    <% elsif @sport.mens_basketball? %>
      <%= render 'shared/sidebar_mens_basketball' %>
    <% elsif @sport.football? %>
      <%= render 'shared/sidebar_football' %>
    <% end %>
  </div>
<% end %>

app/views/shared/_sidebar_football.html.erb
<nav class="sidebar">
  <ul>
    <li class="dropdown">
      <a class="dropdown-toggle" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        Who We Are
      </a>
      <ul class="dropdown-menu">
        <li><a href="<%= football_about_path %>">About Us</a></li>
        <li><a href="<%= football_team_path %>">Meet Our Team</a></li>
        <li><a href="<%= football_testimonials_path %>">Testimonials</a></li>
      </ul>
    </li>
    
    <li class="dropdown">
      <a class="dropdown-toggle" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        What We Do
      </a>
      <ul class="dropdown-menu">
        <li><a href="<%= football_professional_management_path %>">Professional Management</a></li>
        <li><a href="<%= football_marketing_path %>">Marketing Management</a></li>
        <li><a href="<%= football_career_path %>">Career Development</a></li>
        <li><a href="<%= football_wealth_management_path %>">Wealth Management</a></li>
      </ul>
    </li>

    <li class="dropdown">
      <a class="dropdown-toggle" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        Clients
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to 'NFL', football_nfl_path %></li>
        <li><%= link_to 'Free Agent', football_free_agent_path %></li>
      </ul>
    </li>

    <li><a href="#">Contact Us</a></li>
  </ul>
</nav>
<footer>
  <ul class="social-media-icons">
    <li>
      <a href="https://twitter.com/SportsIntGroup" class="twitter" target="_blank">
        <%= fa_icon "twitter 2x" %>
      </a>
    </li>
  </ul>
  <ul>
    <li class="footer-links"><a href="http://www.nfl.com/">NFL</a></li>
  </ul>
  <p>&copy; SIG Sports</p>
</footer>

app/views/shared/_sidebar_mens_basketball.html.erb
<nav>
  <ul>
    <li class="dropdown">
      <a class="dropdown-toggle" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        Who We Are
      </a>
      <ul class="dropdown-menu">
        <li><a href="<%= mens_basketball_about_path %>">About Us</a></li>
        <li><a href="<%= mens_basketball_team_path %>">Meet Our Team</a></li>
        <li><a href="<%= mens_basketball_testimonials_path %>">Testimonials</a></li>
      </ul>
    </li>

    <li class="dropdown">
      <a class="dropdown-toggle" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        What We Do
      </a>
      <ul class="dropdown-menu">
        <li><a href="<%= mens_basketball_draft_path %>">NBA Draft Preparation</a></li>
        <li><a href="<%= mens_basketball_training_path %>">Professional Training</a></li>
        <li><a href="<%= mens_basketball_marketing_path %>">Marketing &amp; Philanthropy</a></li>
        <li><a href="<%= mens_basketball_career_path %>">Career Development</a></li>
      </ul>
    </li>

    <li><a href="<%= mens_basketball_path %>">Clients</a></li>
    <li><a href="#">Contact Us</a></li>
  </ul>
</nav>
<footer>
  <ul class="social-media-icons">
    <li>
      <a href="https://twitter.com/SportsIntGroup" class="twitter" target="_blank">
        <%= fa_icon "twitter 2x" %>
      </a>
    </li>
    <li>
      <a href="https://www.youtube.com/user/SigSportsInc" class="youtube" target="_blank">
        <%= fa_icon "youtube 2x" %>
      </a>
    </li>
  </ul>
  <ul>
    <li class="footer-links"><a href="http://www.fibaeurope.com/default.asp">FIBA</a></li>
     <li class="footer-links"> I </li>
    <li class="footer-links"><a href="http://www.nba.com/">NBA</a></li>
  </ul>
  <p>&copy; SIG Sports</p>
</footer>

app/views/shared/_sidebar_womens_basketball.html.erb
<nav>
  <ul>
    <li class="dropdown">
      <a class="dropdown-toggle" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        Who We Are
      </a>
      <ul class="dropdown-menu">
        <li><a class="womens-about" href="<%= womens_basketball_about_path %>">About Us</a></li>
        <li><a class="womens-team" href="<%= womens_basketball_team_path %>">Meet Our Team</a></li>
        <li><a class="womens-testimonials" href="<%= womens_basketball_testimonials_path %>">Testimonials</a></li>
      </ul>
    </li>

    <li class="dropdown">
      <a class="dropdown-toggle" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        What We Do
      </a>
      <ul class="dropdown-menu">
        <li><a class="womens-professional-management" href="<%= womens_basketball_professional_management_path %>">Professional Management</a></li>
        <li><a class="womens-career" href="<%= womens_basketball_career_path %>">Career Development</a></li>
        <li><a class="womens-personal-management" href="<%= womens_basketball_personal_management_path %>">Personal Management</a></li>
        <li><a class="womens-marketing" href="<%= womens_basketball_marketing_path %>">Marketing &amp; Philanthropy</a></li>
      </ul>
    </li>

    <li class="dropdown">
      <a class="dropdown-toggle" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        Clients
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to 'WNBA', womens_basketball_wnba_path, class: 'wnba' %></li>
        <li><%= link_to 'Professional Overseas', womens_basketball_overseas_path, class: 'overseas' %></li>
      </ul>
    </li>

    <li><a href="#">Contact Us</a></li>
  </ul>
</nav>
<footer>
  <ul class="social-media-icons">
    <li>
      <a href="https://twitter.com/SportsIntGroup" class="twitter" target="_blank">
        <%= fa_icon "twitter 2x" %>
      </a>
    </li>
    <li>
      <a href="https://www.youtube.com/user/SigSportsInc" class="youtube" target="_blank">
        <%= fa_icon "youtube 2x" %>
      </a>
    </li>
  </ul>
  <ul>
    <li class="footer-links"><a href="http://www.fibaeurope.com/default.asp">FIBA</a></li>
     <li class="footer-links"> I </li>
    <li class="footer-links"><a href="http://www.wnba.com/">WNBA</a></li>
  </ul>
  <p>&copy; SIG Sports</p>
</footer>