config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :admin_users
    resources :athletes
    resources :featured_photos
    resources :news_articles
    resources :sports, only: [:index, :show]
    resources :testimonials

    root to: "admin_users#index"
  end

  devise_for :admin_users

  root to: 'pages#index'

  resources :news_articles
  resources :featured_photos
  resources :athletes

  get '/womens-basketball', to: 'sports#womens_basketball'
  get '/mens-basketball', to: 'sports#mens_basketball'
  get '/football', to: 'sports#football'

  get '/womens-basketball/featured', to: 'sports#womens_basketball_featured'
  get '/mens-basketball/featured', to: 'sports#mens_basketball_featured'
  get '/football/featured', to: 'sports#football_featured'

  get 'womens-basketball/wnba', to: 'sports#womens_basketball_wnba'
  get 'womens-basketball/overseas', to: 'sports#womens_basketball_overseas'

  get 'football/nfl', to: 'sports#football_nfl'
  get 'football/free-agent', to: 'sports#football_free_agent'

  get '/womens-basketball/about', to: 'pages/womens_basketball#about'
  get '/womens-basketball/team', to: 'pages/womens_basketball#team'
  get '/womens-basketball/testimonials', to: 'pages/womens_basketball#testimonials'

  get '/womens-basketball/professional-management', to: 'pages/womens_basketball#professional_management'
  get '/womens-basketball/career', to: 'pages/womens_basketball#career_development'
  get '/womens-basketball/personal-management', to: 'pages/womens_basketball#personal_management'
  get '/womens-basketball/marketing', to: 'pages/womens_basketball#marketing'

  get '/womens-basketball/contact', to: 'pages/womens_basketball#contact'

  get '/mens-basketball/about', to: 'pages/mens_basketball#about'
  get '/mens-basketball/team', to: 'pages/mens_basketball#team'
  get '/mens-basketball/testimonials', to: 'pages/mens_basketball#testimonials'

  get '/mens-basketball/draft', to: 'pages/mens_basketball#draft_preparation'
  get '/mens-basketball/training', to: 'pages/mens_basketball#training'
  get '/mens-basketball/marketing', to: 'pages/mens_basketball#marketing'
  get '/mens-basketball/career', to: 'pages/mens_basketball#career_development'

  get '/mens-basketball/contact', to: 'pages/mens_basketball#contact'

  get '/football/about', to: 'pages/football#about'
  get '/football/team', to: 'pages/football#team'
  get '/football/testimonials', to: 'pages/football#testimonials'

  get '/football/professional-management', to: 'pages/football#professional_management'
  get '/football/marketing', to: 'pages/football#marketing'
  get '/football/career', to: 'pages/football#career_development'
  get '/football/wealth-management', to: 'pages/football#wealth_management'

  get '/football/contact', to: 'pages/football#contact'

  
  get 'boris', to: 'pages/womens_basketball#boris'
  get 'carolina', to: 'pages/womens_basketball#carolina'
  get 'ticha', to: 'pages/womens_basketball#ticha'
  get 'sammy', to: 'pages/womens_basketball#sammy'
  get 'jonathan', to: 'pages/womens_basketball#jonathan'

  get 'boris-mens', to: 'pages/mens_basketball#boris', as: 'boris_mens'
  get 'michael', to: 'pages/mens_basketball#michael', as: 'michael'
  get 'sammy-mens', to: 'pages/mens_basketball#sammy', as: 'sammy_mens'
  get 'jonathan-mens', to: 'pages/mens_basketball#jonathan', as: 'jonathan_mens'

  get 'boris-football', to: 'pages/football#boris', as: 'boris_football'
  get 'chad', to: 'pages/football#chad'

end

app/controllers/pages/football_controller.rb
class Pages::FootballController < ApplicationController
  before_action :set_sport

  def testimonials
    @testimonials = Testimonial.all
  end

private
  def set_sport
    @sport = Sport.find_by_type_id(2)
  end
end

app/views/pages/football/about.html.erb
<main>
  <section id="about">
    <h1>About Us</h1>
    <article>
      <p>The mission of Sports International Group is to provide our clients with the opportunity to excel throughout their career by serving their needs both on and off the field.</p>

      <p>We are a family company that believes in hard work, dedication, communication and integrity, and providing the very best quality of service.</p>
    </article>
    <h3 id="slogan">Taking you to the next level...</h3>
  </section>
</main>

app/views/pages/football/boris.html.erb
<main class="team-member">
  <section class="image-container">
    <figure>
      <%= image_tag 'team/boris.jpg', alt: 'Boris', class: 'grid-item-image' %>
    </figure>
  </section>

  <section class="description">
    <h1>Boris Lelchitski</h1>
    <h2 class="red uppercase">FOUNDER &amp; CEO</h2>

    <p>With over thirty years of experience in the sports industry, Boris Lelchitski has established himself as one of the top sports agents in the world. In 1996, Boris founded Sports International Group, and has since managed the careers of numerous high-profile professional basketball players and coaches.</p>

    <br />

    <p>Since 2006, Boris has developed SIG into one of the most respected and dynamic agencies in the professional basketball world.  Specializing in women’s basketball, Boris client list now includes some of the top athletes in the sport. SIG represents over 30 players in the WNBA, including WNBA Champions, Most Valuable Players, All-Stars and Rookies of the Year. Internationally, SIG represents numerous high-profile clients who have won European Championships, Olympic Medals, World Championship Medals as well as Euroleague and Eurocup Club championships.</p>

    <br />

    <p>Boris has developed an incredible reputation in the professional basketball world through his dedication and high level of integrity, as well as the results tBorihe gets for his clients. No other agency can come close to the amount of success that SIG has had over the last 15 years. SIG’s clients consistently receive top-dollar contracts and are provided with a personal service that is unmatched in the industry. This combination is why SIG’s clients are the happiest and most successful in the business. Boris has negotiated record-setting contracts for women’s basketball players and SIG’s women’s basketball clients consistently earn a combined average of over $15million per season. These proven results are what separate Boris from the competition and place him in an elite category.</p>

    <br />

    <p>Prior to founding SIG, Boris spent the majority of his career coaching in Russia and the United States. While in Russia, he was the head coach of Spartak, St. Petersburg for eleven years. During that span, Spartak was a major competitor in the Euroleague. After coming to the United States, Boris spent three years as Head Women’s Basketball Coach at Heathwood Hall Academy, and five years coaching AAU Basketball in Columbia, South Carolina. During his coaching career, Boris won over 500 games and numerous conference and state championships on the amateur and pro levels.</p>

    <br />

    <p>Boris holds a Master’s Degree in Basketball Coaching from Lesgaft Academy of Physical Education in St. Petersburg, Russia and an associate’s degree in Sports Administration from the University of South Carolina.</p>
 
  </section>

</main>

app/views/pages/football/career_development.html.erb
<main class="what-we-do">
  <h1>CAREER DEVELOPMENT</h1>

  <h2>Combine &amp; NFL Draft Preparation</h2>

  <p>The scouting combine and the NFL Draft represent your entryway into the NFL. SIG will help you prepare both physically and mentally for the rigors of the workouts. We’ll match you with a special weight and speed training program to increase your performance. We’ll review and run down all the position drills so you’ll go in with the confidence of knowing exactly what’s expected. And we’ll schedule your team workouts so you’re always performing at your best.</p>

  <h2>Other SIG Services:</h2>
  <ul>
    <li>Preparation for team interviews</li>
    <li>Real estate acquisition and financing</li>
    <li>Assistance in obtaining a line of credit</li>
    <li>Individual estate and gift tax planning</li>
    <li>Bank account reconciliation and management</li>
    <li>Post sports career development</li>
  </ul>

  <h3 id="slogan">Taking you to the next level...</h3>
</main>

app/views/pages/football/chad.html.erb
<main class="team-member">
  <section class="image-container">
    <figure>
      <%= image_tag 'team/chad.jpg', alt: 'Chad', class: 'grid-item-image' %>
    </figure>
  </section>

  <section class="description">
    <h1>Chad E. Wiestling</h1>
    <h2 class="red uppercase">President of SIG Football</h2>

    <p>Recently being acquired and named President of SIG Football in May 2012, Chad comes to the company both highly recommended and respected in the industry by his peers with an incredible wealth of football intelligence.</p>

    <br />

    <p>He is a former captain of the University of Maryland football team where he earned his bachelors degree.  While attending graduate school, he coached at his alma mater for three NCAA seasons as a graduate assistant. After playing four seasons in the Arena Football League, Chad took his football knowledge to the National Football League where he worked in the front office of two NFL organizations.</p>

    <br />

    <p>Prior to arriving at SIG, Chad was a partner at a very successful sports agency, Integrated Sports Management, which was founded in 1996 with the focus solely on representing professional football players. He has represented players drafted in every round on the NFL draft and currently brings players such as Muhammad Wilkerson (1st Round), Tavon Wilson (2nd round), Julius Jones (2nd Round), Nolan Carroll (5th Round), and Moise Fokou (7th Round) to the company.</p>

    <br />

    <p>Chad is very excited about bringing his football experience to Sports International Group. He is also extremely proud of his achievements in recruiting and representing top quality men in all of the professional football leagues.</p>
 
  </section>

</main>

app/views/pages/football/marketing.html.erb
<main class="what-we-do">
  <h1>Marketing Management</h1>

  <h2>Personality Marketing &amp; Endorsements</h2>

  <p>There's a difference between being a gifted athlete and a marketable personality. At SIG, we can help clients showcase their best "people skills." One way to do this is to encourage our clients to become involved in their communities. Another way is to retain speech or acting coaches for clients when necessary. Still another way is to retain publicists to maximize public exposure opportunities. All this may seem more "showbiz" than sports oriented, but the lines between the two worlds are very thin indeed.</p>

  <p>At SIG we are always on the lookout for marketing possibilities, from athletic apparel endorsements and other national advertising contracts to local appearances and community oriented activities. Our creative drive has led to many new opportunities for our clients and their friends and families.</p>

  <h3 id="slogan">Taking you to the next level...</h3>  
</main>

app/views/pages/football/professional_management.html.erb
<main class="what-we-do">
  <h1>PROFESSIONAL MANAGEMENT</h1>

  <p>The Sports International Group, Inc. football division is a full service management company. We are unique to the sports management world because our roots are an equal mixture of certified contract negotiation, personality marketing and endorsements, and all aspects of financial management. Our goal is to maximize your annual income and net worth as well as build your portfolio to insure financial security long after the conclusion of your career as a professional athlete. We strongly believe in putting our client’s needs above everything else. Our approach to client service is geared to ensure that you and your family will maintain a high quality of life long after your playing days are over.</p>

  <p>Your SIG team is built around you and your individual needs. Together, we’ll maximize your income and net worth and help you realize your goals. Uncle Sam can sometimes be an unwelcome relative. We’ll help you through the maze and maximize your liabilities. The scouting combine is your NFL job interview. We’ll get you ready both physically and mentally.</p>

  <h3 id="slogan">Taking you to the next level...</h3>  
</main>

app/views/pages/football/team.html.erb
<main>
  <section id="team" class="football">
  <ul>
    <li>
      <a href="<%= boris_football_path %>">
        <figure>
          <%= image_tag 'team/boris.jpg', alt: 'Boris', class: 'grid-item-image' %>
        </figure>
        <h2>Boris Lelchitski</h2>
        <h3 class="red">FOUNDER &amp; CEO</h3>
      </a>
      <footer>
        <ul class="team-social-media-icons">
          <li class="one-icon">
            <a href="mailto:Borissig@aol.com"><%= fa_icon "envelope-o", class: "email" %></a>
          </li>
        </ul>
      </footer>
    </li>
    
    <li>
      <a href="<%= chad_path %>">
        <figure>
          <%= image_tag 'team/chad.jpg', alt: 'Chad', class: 'grid-item-image' %>
        </figure>
        <h2>Chad E. Wiestling</h2>
        <h3 class="red">President of SIG Football</h3>
      </a>
      <footer>
        <ul class="team-social-media-icons">
          <li class="one-icon">
            <a href="mailto:wiestling@sigsports.com"><%= fa_icon "envelope-o", class: "email" %></a>
          </li>
        </ul>
      </footer>
    </li>
  </ul>
  </section>
</main>

app/views/pages/football/wealth_management.html.erb
<main class="what-we-do">
  <h1>Wealth Development</h1>

  <h2>Contract Negotiations</h2>

  <p>When SIG sits down at the bargaining table with a future employer on your behalf, it's good to know you've got proven experience on your side. Experience that has made us one of the top sports management companies in the u.s. Experience that includes generating a signing bonus for a client that was the largest in the history of the NFL franchise with whom we were dealing.</p>

  <p>SIG has a solid knowledge of the NFL collective bargaining agreement. We perform extensive research on prior year contracts, the current rookie cap and the overall salary ceiling for each team. We are equipped with statistical and other data to negotiate the best possible contract on your behalf. And since SIG is home to both a certified public accountant and a certified contract negotiator, we are able to structure contracts that not only meet financial needs, but also minimize tax burden.</p>

  <h2>Business Management</h2>

  <p>Negotiating the best possible contract is only part of the picture. After the contract has been signed, your money needs to be administered properly. We educate our clients on how to live within their means, make smart investments and financially prepare for life after sports. Ultimately, you the client have full control over your finances. But since we have been serving clients for several years, we are experienced in the highs, lows, achievable goals and unrealistic expectations sudden wealth can mean.</p>

  <h2>Annual Tax Preparation</h2>

  <p>SIG has prepared hundreds of federal and state income tax returns for professional athletes. We're experts in preparing tax returns and our cost for this service is included in our fees for contract negotiation. In other words, there's no hidden charge for this service. Athletes frequently have distinct and complex financial issues and nobody knows how to untie and explain these issues better than SIG. It's also good to know that the people who do your taxes are the same people implementing and administering your financial plans.</p>

  <p>We supply each client with a monthly statement - a careful system of checks and balances to ensure your financial team is working together and that your interests are being well-served.</p>

  <h3 id="slogan">Taking you to the next level...</h3>
</main>